os: osx
osx_image: xcode11.3
language: Swift
script: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.3,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO